
const ACTION_TYPES = {
    ADD_CONTENT: 'ADD_CONTENT',
    REMOVE_CONTENT: 'REMOVE_CONTENT',
    EDIT_CONTENT: 'EDIT_CONTENT',
    ADD_VOTE: 'ADD_VOTE',
    REMOVE_VOTE: 'REMOVE_VOTE',
};

const EMPTY_CONTENT_HTML_OPTIONS = ['<br>', '<span></span>', '<h1><br></h1>', '<h1></h1>'];

export { ACTION_TYPES, EMPTY_CONTENT_HTML_OPTIONS};